# Generated by Django 4.2.6 on 2023-12-24 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_seller_alter_product_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_type', models.IntegerField(default=0, null=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.warrantyproduct'),
        ),
    ]
